### PR TITLE
Add docker builds

### PR DESCRIPTION
**Pull request by Skelmis**
*This is a work in progress, I can finish it once I get home next week and have actual time to debug ffmpeg docker builds.*

This PR add's in a github action for building and publishing a docker image on commit. The image itself runs the bot.

#33

### CODE REVIEW

**Comment by squigjess** [comment]
Moving to the `testing` branch to ensure that the branches don't get mixed up.

**Comment by Skelmis** [comment]
Yea, I started work this week so as it turns out. No time : )

Will let you know when I do though

**Comment by Skelmis** [comment]
This works. Just needs to be changed branches

Also requires full testing but i don't have the time for a setup. Can you try?

**Comment by squigjess** [comment]
Works for me on the current testing branch, lgtm ✨

**Pull request merged**
